# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bdf22d9f5111070282b86e6ba7815e132aabfe580b7493a4d55384a52a2e871033b95819bfec9ce3c225aa6ba7fe684f0b4a97ee3144b07313dfa68d12b4c35

test:
  secret_key_base: be8ff995905b7fc7f697054c7e2d7426e4a9671189dae602cb01983cf5aaa73df60919d1d732b707b240b18b72676ec6216ab47b0f94560300d583511c62aab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
